# Generated by Django 2.0.5 on 2018-06-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('card_name', models.CharField(max_length=128)),
                ('name_on_card', models.CharField(max_length=32)),
                ('expiry_date', models.CharField(max_length=5)),
                ('card_type', models.CharField(max_length=128)),
                ('cvv', models.IntegerField()),
                ('card_number', models.CharField(max_length=16)),
            ],
        ),
    ]
